apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
data:
  CEPHCSI: |
    channel: alpha
    csv: cephcsi-operator.v4.19.0
    pkg: cephcsi-operator
    scaleUpOnInstanceOf:
      - cephclusters.ceph.rook.io
  CSIADDONS: |
    channel: alpha
    csv: csi-addons.v0.12.0
    pkg: csi-addons
    scaleUpOnInstanceOf:
      - cephclusters.ceph.rook.io
  IBM: |
    channel: stable-v1.7
    csv: ibm-storage-odf-operator.v1.7.0
    pkg: ibm-storage-odf-operator
    scaleUpOnInstanceOf:
      - flashsystemclusters.odf.ibm.com
  NOOBAA: |
    channel: alpha
    csv: noobaa-operator.v5.19.0
    pkg: noobaa-operator
    scaleUpOnInstanceOf:
      - noobaas.noobaa.io
  OCS_CLIENT: |
    channel: alpha
    csv: ocs-client-operator.v4.19.0
    pkg: ocs-client-operator
    scaleUpOnInstanceOf:
      - cephclusters.ceph.rook.io
  OCS: |
    channel: alpha
    csv: ocs-operator.v4.19.0
    pkg: ocs-operator
    scaleUpOnInstanceOf:
      - storageclusters.ocs.openshift.io
  ODF_DEPS: |
    channel: alpha
    csv: odf-dependencies.v4.19.0
    pkg: odf-dependencies
  PROMETHEUS: |
    channel: beta
    csv: odf-prometheus-operator.v4.19.0
    pkg: odf-prometheus-operator
    scaleUpOnInstanceOf:
      - alertmanagers.monitoring.coreos.com
      - prometheuses.monitoring.coreos.com
  RECIPE: |
    channel: alpha
    csv: recipe.v0.0.1
    pkg: recipe
  ROOK: |
    channel: alpha
    csv: rook-ceph-operator.v4.19.0
    pkg: rook-ceph-operator
    scaleUpOnInstanceOf:
      - cephclusters.ceph.rook.io
