apiVersion: v1
data:
  CEPHCSI: |
    channel: alpha
    csv: cephcsi-operator.v4.18.0
    pkg: cephcsi-operator
    scalerCrds:
      - cephclusters.ceph.rook.io
  CEPHCSI_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  CEPHCSI_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  CEPHCSI_SUBSCRIPTION_CHANNEL: alpha
  CEPHCSI_SUBSCRIPTION_NAME: cephcsi-operator
  CEPHCSI_SUBSCRIPTION_PACKAGE: cephcsi-operator
  CEPHCSI_SUBSCRIPTION_STARTINGCSV: cephcsi-operator.v4.18.0
  CSIADDONS: |
    channel: alpha
    csv: csi-addons.v0.10.0
    pkg: csi-addons
    scalerCrds:
      - cephclusters.ceph.rook.io
  CSIADDONS_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  CSIADDONS_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  CSIADDONS_SUBSCRIPTION_CHANNEL: alpha
  CSIADDONS_SUBSCRIPTION_NAME: csi-addons
  CSIADDONS_SUBSCRIPTION_PACKAGE: csi-addons
  CSIADDONS_SUBSCRIPTION_STARTINGCSV: csi-addons.v0.10.0
  IBM: |
    channel: stable-v1.6
    csv: ibm-storage-odf-operator.v1.6.0
    pkg: ibm-storage-odf-operator
    scalerCrds:
      - flashsystemclusters.odf.ibm.com
  IBM_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  IBM_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  IBM_SUBSCRIPTION_CHANNEL: stable-v1.6
  IBM_SUBSCRIPTION_NAME: ibm-storage-odf-operator
  IBM_SUBSCRIPTION_PACKAGE: ibm-storage-odf-operator
  IBM_SUBSCRIPTION_STARTINGCSV: ibm-storage-odf-operator.v1.6.0
  NOOBAA: |
    channel: alpha
    csv: noobaa-operator.v5.18.0
    pkg: noobaa-operator
    scalerCrds:
      - noobaas.noobaa.io
  NOOBAA_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  NOOBAA_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  NOOBAA_SUBSCRIPTION_CHANNEL: alpha
  NOOBAA_SUBSCRIPTION_NAME: noobaa-operator
  NOOBAA_SUBSCRIPTION_PACKAGE: noobaa-operator
  NOOBAA_SUBSCRIPTION_STARTINGCSV: noobaa-operator.v5.18.0
  OCS: |
    channel: alpha
    csv: ocs-operator.v4.18.0
    pkg: ocs-operator
    scalerCrds:
      - storageclusters.ocs.openshift.io
  OCS_CLIENT: |
    channel: alpha
    csv: ocs-client-operator.v4.18.0
    pkg: ocs-client-operator
  OCS_CLIENT_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  OCS_CLIENT_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  OCS_CLIENT_SUBSCRIPTION_CHANNEL: alpha
  OCS_CLIENT_SUBSCRIPTION_NAME: ocs-client-operator
  OCS_CLIENT_SUBSCRIPTION_PACKAGE: ocs-client-operator
  OCS_CLIENT_SUBSCRIPTION_STARTINGCSV: ocs-client-operator.v4.18.0
  OCS_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  OCS_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  OCS_SUBSCRIPTION_CHANNEL: alpha
  OCS_SUBSCRIPTION_NAME: ocs-operator
  OCS_SUBSCRIPTION_PACKAGE: ocs-operator
  OCS_SUBSCRIPTION_STARTINGCSV: ocs-operator.v4.18.0
  ODF_DEPS: |
    channel: alpha
    csv: odf-dependencies.v4.19.0
    pkg: odf-dependencies
  ODF_DEPS_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  ODF_DEPS_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  ODF_DEPS_SUBSCRIPTION_CHANNEL: alpha
  ODF_DEPS_SUBSCRIPTION_NAME: odf-dependencies
  ODF_DEPS_SUBSCRIPTION_PACKAGE: odf-dependencies
  ODF_DEPS_SUBSCRIPTION_STARTINGCSV: odf-dependencies.v4.19.0
  PROMETHEUS: |
    channel: beta
    csv: odf-prometheus-operator.v4.18.0
    pkg: odf-prometheus-operator
    scalerCrds:
      - alertmanagers.monitoring.coreos.com
      - prometheuses.monitoring.coreos.com
  PROMETHEUS_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  PROMETHEUS_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  PROMETHEUS_SUBSCRIPTION_CHANNEL: beta
  PROMETHEUS_SUBSCRIPTION_NAME: odf-prometheus-operator
  PROMETHEUS_SUBSCRIPTION_PACKAGE: odf-prometheus-operator
  PROMETHEUS_SUBSCRIPTION_STARTINGCSV: odf-prometheus-operator.v4.18.0
  RECIPE: |
    channel: alpha
    csv: recipe.v0.0.1
    pkg: recipe
  RECIPE_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  RECIPE_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  RECIPE_SUBSCRIPTION_CHANNEL: alpha
  RECIPE_SUBSCRIPTION_NAME: recipe
  RECIPE_SUBSCRIPTION_PACKAGE: recipe
  RECIPE_SUBSCRIPTION_STARTINGCSV: recipe.v0.0.1
  ROOK: |
    channel: alpha
    csv: rook-ceph-operator.v4.18.0
    pkg: rook-ceph-operator
    scalerCrds:
      - cephclusters.ceph.rook.io
  ROOK_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  ROOK_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  ROOK_SUBSCRIPTION_CHANNEL: alpha
  ROOK_SUBSCRIPTION_NAME: rook-ceph-operator
  ROOK_SUBSCRIPTION_PACKAGE: rook-ceph-operator
  ROOK_SUBSCRIPTION_STARTINGCSV: rook-ceph-operator.v4.18.0
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceName: 4fd470de.openshift.io
kind: ConfigMap
metadata:
  name: odf-operator-manager-config
